# Generated by Django 4.0 on 2022-11-11 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_website',
        ),
    ]
