# Generated by Django 4.0 on 2022-11-11 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_social_youtube_profile_social_stackoverflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_stackoverflow',
            new_name='social_discord',
        ),
    ]
