# Generated by Django 4.2.6 on 2024-02-27 09:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dzgo6p5ob/image/upload/v1708857993/efw92dfcfz1zlluayqrv.jpg', max_length=255, verbose_name='users/'),
        ),
    ]
