# Generated by Django 4.2.6 on 2024-02-27 09:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_options_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dzgo6p5ob/image/upload/v1708865333/static/images/profiles/user-default.jpg', max_length=255, verbose_name='users/'),
        ),
    ]
