# Generated by Django 4.0 on 2023-03-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_social_stackoverflow_profile_social_discord'),
        ('projects', '0003_alter_project_options_review_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('owner', 'project')},
        ),
    ]
