# Generated by Django 4.2.6 on 2024-02-27 09:15

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_options_alter_profile_profile_image'),
        ('projects', '0005_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dzgo6p5ob/image/upload/v1708858008/aiuxvzo7lemtrqomrk2u.jpg', max_length=255, verbose_name='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
