# Generated by Django 4.2.6 on 2024-02-27 09:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_featured_image_alter_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dzgo6p5ob/image/upload/v1708865324/static/images/default.jpg', max_length=255, verbose_name='projects/'),
        ),
    ]
